version: '3.1'

services:
  dpsrv-zookeeper:
    container_name: dpsrv-zookeeper-${tag:-latest}
    image: zookeeper:3.7.2
    restart: unless-stopped
    hostname: $HOSTNAME.dpsrv.me
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=$HOSTNAME:2888:3888;2181
networks:
  default:
    name: dpsrv
    external: true
